repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: "check-case-conflict"
      - id: "check-merge-conflict"
      - id: "debug-statements"
      - id: "end-of-file-fixer"
      - id: "mixed-line-ending"
      - id: "detect-private-key"
      - id: "check-yaml"
      - id: "check-toml"
      - id: "check-json"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.1.11'
    hooks:
      - id: ruff
      - id: ruff-format
        name: ruff-format
        description: "Run 'ruff format' for extremely fast Python formatting"
        entry: ruff format --force-exclude
        language: python
        types_or: [ python, pyi ]
        args: [ ]
        require_serial: true
        additional_dependencies: [ ]
        minimum_pre_commit_version: "2.9.2"
